language: ruby
cache: bundler

rvm:
  - 2.4

script:
  - ./bin/test_site.sh
  - bundle exec jekyll algolia # Update search index

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

branches:
  only:
  - master
